# Generated by Django 4.2.23 on 2025-07-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=255)),
                ("level", models.CharField(max_length=50)),
                ("session_id", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="ContextFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="context_files/")),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="ExamFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="exam_files/")),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
