# Generated by Django 4.2.23 on 2025-07-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airesult",
            name="file_path",
        ),
        migrations.AddField(
            model_name="airesult",
            name="file",
            field=models.FileField(default="", upload_to="ai_results/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="airesult",
            name="level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="examfile",
            name="session_id",
            field=models.CharField(max_length=40),
        ),
    ]
