# Generated by Django 4.2.23 on 2025-07-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_password_hash", models.CharField(max_length=128)),
                ("openai_api_key", models.CharField(max_length=100)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "Deutsch")],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("setup_complete", models.BooleanField(default=False)),
            ],
        ),
    ]
