# Generated by Django 4.2.23 on 2025-07-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_simulation_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appconfig",
            name="openai_api_key",
            field=models.CharField(max_length=200),
        ),
    ]
